### ISSUE TITLE
add latest articles widget to module

### ISSUE THREAD

**Issue by masihfathi** [cinghie/yii2-articles#11]
i added a latest article widget to your module (yii2-articles). do you want to added this widget to the main module?
![latest-artice](https://cloud.githubusercontent.com/assets/13271510/24353771/642e859c-1304-11e7-97d3-1b67aee0268c.jpg)

**Comment by cinghie** [comment]
Hi @masihfathi,

you can do a Pull Request to contribute to this project with your code.
