### ISSUE TITLE
403 error 

### ISSUE THREAD

**Issue by iceprox** [cinghie/yii2-articles#13]
403 error on all actions except articles

**Comment by cinghie** [comment]
Hi @iceprox,

is problem of auth permission.

I'm implementing auth migration to fix the problem

**Comment by cinghie** [comment]
Closed on last dev release

**Comment by nashpb** [comment]
Im still getting the forbidden 403 error. I have migrated the tables, im have signed in using dektrium user and rbac. What might be the cause of the problem?
