### ISSUE TITLE
upload video

### ISSUE THREAD

**Issue by masihfathi** [cinghie/yii2-articles#18]
thanks for your work, why did not add upload video like image and sth else is it possible add sth like extra field to article item table by just adding filed by admin not by developer cause some times some fields may need in a specefic case and for specefic user.

**Comment by cinghie** [comment]
Hi @masihfathi,

thanks for your request; i added your request like two new sepate issues,
scheduled on milestones 0.7.0 (video field) and 0.9.0 (custom fields).

I think the first one will be very fast to implement while the other is programmed for a not very near future. If you want to collaborate to implement it your are welcome.
