### ISSUE TITLE
Error when passing in the category

### ISSUE THREAD

**Issue by Robot72** [cinghie/yii2-articles#2]
Hello!!!
I have the following error POPs up:
Call to undefined method kartik\base\Config::initModule()
![2015-02-07 14 13 25](https://cloud.githubusercontent.com/assets/5987937/6091893/820745dc-aed3-11e4-9352-c4afe021cf1a.png)

**Comment by rahman2k9** [comment]
same issue here.! :(

**Comment by cinghie** [comment]
Update version e configuration

**Comment by client510** [comment]
cinghie/yii2 article error 403
