### ISSUE TITLE
utf8 slug problem

### ISSUE THREAD

**Issue by masihfathi** [cinghie/yii2-articles#26]
thanks for your work. when title of article or tag or category is in the utf8 charecter the url make problem. sth should be done with generate alias function and url rule.

**Comment by cinghie** [comment]
Hi @masihfathi 
can you specify better the problem with an example?

**Comment by masihfathi** [comment]
in title of article write for example sth in persian like "مقاله تست" and then see alias which generated.

**Comment by masihfathi** [comment]
i think this library is good for slug:
https://github.com/cocur/slugify

**Comment by cinghie** [comment]
Ok thanks.

i implement it i next version

**Comment by cinghie** [comment]
Hi @masihfathi 

with the last version with a very simple update i have implemented Slugify, 
updating yii2-traits the funcion function setAlias().

In Articles is there now an option named $slugifyOptions.
By default is 

`[
		'separator' => '-',
		'lowercase' => true,
		'trim' => true,
		'rulesets'  => [
			'default'
		]
]`

See in Slugify how set options to set your language.

In the last master, you already have the update.

Can you check?

**Comment by masihfathi** [comment]
when i change yii2 article package to dev-master i got error with composer update:
                                                                               
```
  [Composer\Repository\InvalidRepositoryException]                             
  No valid bower.json was found in any branch or tag of https://github.com/Dm  
  itryBaranovskiy/eve.git, could not load a package from it.             
```      
i think something problem with `cinghie/yii2-admin-lte` in the dependency. and one question why you require `adminilte` and `dektrium/yii2-user` in the yii2 article?
i think it is better to add these dependency optionally by the user. someone may want to use his user component or ... 
and one thing forgotten in the auth permission is the tag's permission for author, editor and  publisher roles.

and at last, your work's are great

**Comment by cinghie** [comment]
Hi @masihfathi ,

I open two separate issues #29 and #28 with your required.

For the dektrium User Module i think is the best User Management for yii2,
and i created a Module to extend his functions.

Then I need this extension but if you want implement this, you're welcome.
