### ISSUE TITLE
Error when migrate Integrity constraint violation: 1452

### ISSUE THREAD

**Issue by uzzielpelawak** [cinghie/yii2-articles#31]
I get error when migrate database

Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`polosan`.`auth_item_child`, CONSTRAINT `auth_item_child_ibfk_2` FOREIGN KEY (`child`) REFERENCES `auth_item` (`name`) ON DELETE CASCADE ON UPDATE CASCADE)
The SQL being executed was: INSERT INTO `auth_item_child` (`parent`, `child`) VALUES ('admin', 'articles-index-tags') (C:\xampp\htdocs\rektnarok\vendor\yiisoft\yii2\db\Schema.php:664)

**Comment by HunWalk** [comment]
https://pastebin.com/84ZZc1bZ
Add those to the end of "//Auth Item Permissions" segment in file: 
vendor/cinghie/yii2-articles/migrations/m170626_185620_insert_article_auth_permissions.php

Notice this @cinghie 

also a minor bug. What if there is no user in the database with id=1? :D the demo data migration also fails. And somewhat the safeDowns aren't really working...

**Comment by cinghie** [comment]
Hi @HunWalk,

1) i have fixed the problem in migrations/m170626_185620_insert_article_auth_permissions.php adding missing rows 

2) I have updated README with an alert before the run command migration istruction:

"Make sure that you have an user with id=1."

Thanks for the issue also to @uzzielpelawak
