### ISSUE TITLE
No Custom Urlmanger Configurations in the docs 

### ISSUE THREAD

**Issue by buttflattery** [cinghie/yii2-articles#32]
Hello i need to ask if there is any custom class or extension used by the `urlManager` configurations as i dont see any in the documentation the default class is used whereas inside the `yii2-traits\LanguageTrait.php` you have the `getLanguagesSelect2()` which calls the first line `$languages = Yii::$app->urlManager->languages;` that would trigger an error in case of the `yii\web\urlManager` class used, as there is no such property for that class

**Comment by cinghie** [comment]
Hi @buttflattery,

thanks I fix the problem improving README and adding required codemix/yii2-localeurls to yii2-traits.

You can all urlManager options on github developer page:

https://github.com/codemix/yii2-localeurls
