### ISSUE TITLE
Plugin breaking with php7

### ISSUE THREAD

**Issue by paulobrandit** [cinghie/yii2-articles#8]
Hi there,
first of all thank you for amazing articles extension. I've been using it for more than one month and I am really happy with it.

I'm just writing this issue / post just to inform that the extension breaks with php 7. The error happens while saving an Item (with file uploaded), and the line trigging the error follows:

cinghie\articles\models\Articles.php , line 56: 
**$fileExt = end((explode(".", $file->name)));**

I've patched it this way:
**$exploded = explode(".", $file->name);
$fileExt = end($exploded);**

Really hope this helps you and once again thank you for your great extension!

more info here:
http://php.net/manual/en/language.references.pass.php
http://php.net/manual/en/function.end.php

**Comment by cinghie** [comment]
Update to last dev version and the line is "$fileExt  = $file->extension;"
